FROM dpage/pgadmin4:latest

# Switch to root to install necessary packages
USER root
RUN apk update && apk add --no-cache curl bash

# Copy the script to the container
COPY pgadmin_setup.sh /app/scripts/pgadmin_setup.sh
RUN chmod +x /app/scripts/pgadmin_setup.sh

# Switch back to the pgadmin user for running PgAdmin
USER pgadmin

# Set environment variables for default login
ENV PGADMIN_DEFAULT_EMAIL=fulano@gmail.com
ENV PGADMIN_DEFAULT_PASSWORD=abc123

# Start PgAdmin and run the setup script
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/app/scripts/pgadmin_setup.sh"]
